// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMYCzit2wKZnaAvHs6fqJqkxWj6ZWhhNo',
    appId: '1:913254759526:web:11102c0cd4322bdb48c1a7',
    messagingSenderId: '913254759526',
    projectId: 'sws-ai-chat',
    authDomain: 'sws-ai-chat.firebaseapp.com',
    storageBucket: 'sws-ai-chat.firebasestorage.app',
    measurementId: 'G-NV5ESXLBH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY29WNttMkzbDKNH0IoOPRRs76NwAMPOE',
    appId: '1:913254759526:android:1600319d8bc24af648c1a7',
    messagingSenderId: '913254759526',
    projectId: 'sws-ai-chat',
    storageBucket: 'sws-ai-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRHPunqmHSfmV11lI9AsXBgy3jb43LACo',
    appId: '1:913254759526:ios:fa2444000cb8a9fb48c1a7',
    messagingSenderId: '913254759526',
    projectId: 'sws-ai-chat',
    storageBucket: 'sws-ai-chat.firebasestorage.app',
    iosBundleId: 'com.example.swsAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRHPunqmHSfmV11lI9AsXBgy3jb43LACo',
    appId: '1:913254759526:ios:fa2444000cb8a9fb48c1a7',
    messagingSenderId: '913254759526',
    projectId: 'sws-ai-chat',
    storageBucket: 'sws-ai-chat.firebasestorage.app',
    iosBundleId: 'com.example.swsAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMYCzit2wKZnaAvHs6fqJqkxWj6ZWhhNo',
    appId: '1:913254759526:web:f658f8ad5549ba8048c1a7',
    messagingSenderId: '913254759526',
    projectId: 'sws-ai-chat',
    authDomain: 'sws-ai-chat.firebaseapp.com',
    storageBucket: 'sws-ai-chat.firebasestorage.app',
    measurementId: 'G-V3MQCRQQFE',
  );
}
